#!/usr/bin/env bash

SCRIPTDIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# We disable automatic compilation here to avoid noisy output from
# Guile, which likes to tell the user that a file was recompiled.
# Recompilation doesn't really matter much here anyway, this is not
# that much code, and the user can precompile all of the toolchain
# sources using `guild compile'.

exec ${GUILE:-guile} \
     --no-auto-compile \
     -L "${SCRIPTDIR}" \
     -e main \
     -s "${SCRIPTDIR}/paaliaq/toolchain/assembler.scm" \
     $@
